name: Run Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies without requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install boto3 botocore moto

      - name: Verify botocore version
        run: |
          python -c "import botocore; print('botocore version:', botocore.__version__)"

      - name: Run unit tests
        run: |
          python -m unittest test_script.py
          python -m unittest test_scriptMoto.py

  deploy:
    name: Run Deployment Script
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Run deployment script
        run: |
          python script.py --bucket objectswithtagsandmetadata --tags category=Novel,Essay status=Published,Draft --metadata author="J.K. Rowling,Isaac Asimov" language=English,French
